### ISSUE TITLE
New version of Cement deprecated CementApp (now App) 

### ISSUE THREAD

**Issue by saapooch** [KarrLab/karr_lab_build_utils#18]
Newest version of Cement CL Tool (version 3.0) no longer uses the class CementApp. The class is now called App. 

Derived from following error on CircleCi:
Traceback (most recent call last):
  File "/usr/local/bin/karr_lab_build_utils3", line 7, in <module>
    from karr_lab_build_utils.__main__ import main
  File "/usr/local/lib/python3.6/site-packages/karr_lab_build_utils/__main__.py", line 9, in <module>
    from cement.core.foundation import CementApp
ImportError: cannot import name 'CementApp'

**Comment by jonrkarr** [comment]
All packages have been updated to cement 3.0.0
