### ISSUE TITLE
libjvm.so path varies in different environment

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/karr_lab_build_utils#37]
jnius gives error message: 

> SystemError: Error calling dlopen(b'/usr/lib/jvm/java-11-openjdk-amd64/jre/lib/amd64/server/libjvm.so': b'/usr/lib/jvm/java-11-openjdk-amd64/jre/lib/amd64/server/libjvm.so: cannot open shared object file: No such file or directory' 

because the directory 'JAVA_HOME/jre/lib/amd64/server/libjvm.so' is 'JAVA_HOME/lib/server/libjvm.so' in ubuntu 18.04 with openjdk-11. Temporary solution is to create symlinks

**Comment by jonrkarr** [comment]
Can you describe more context for the error?

**Comment by lzy7071** [comment]
The error did not occur in docker image. It occurred following the installation instructions found here: [https://docs.karrlab.org/karr_lab_build_utils/master/0.0.13/installation.html](url) The environment in which it occurred was the native OS of the user, which happened to be Ubuntu 18.04 with openjdk-11 installed from the aptitude repo. Following the success of the installation, running 

> "karr_lab_build_utils create-package"
in the above mentioned environment will return the error message.

**Comment by jonrkarr** [comment]
Build utils doesn't use java. 

Can you copy the full error message?

**Comment by lzy7071** [comment]
> Build utils doesn't use java.
> 
> Can you copy the full error message?

> Traceback (most recent call last):
  File "/home/zl/.conda/envs/py36/bin/karr_lab_build_utils", line 11, in <module>
    load_entry_point('karr-lab-build-utils', 'console_scripts', 'karr_lab_build_utils')()
  File "/home/zl/.conda/envs/py36/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/zl/.conda/envs/py36/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/zl/.conda/envs/py36/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/zl/.conda/envs/py36/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/zl/karr_lab/karr_lab_build_utils/karr_lab_build_utils/__init__.py", line 8, in <module>
    from .core import (CoverageType, Environment,
  File "/home/zl/karr_lab/karr_lab_build_utils/karr_lab_build_utils/core.py", line 34, in <module>
    import karr_lab_build_utils.config.core
  File "/home/zl/karr_lab/karr_lab_build_utils/karr_lab_build_utils/config/core.py", line 12, in <module>
    import wc_utils.config.core
  File "/home/zl/karr_lab/wc_utils/wc_utils/__init__.py", line 8, in <module>
    from . import config
  File "/home/zl/karr_lab/wc_utils/wc_utils/config/__init__.py", line 1, in <module>
    from .core import ConfigPaths, ConfigManager, InvalidConfigError, ExtraValuesError, get_config
  File "/home/zl/karr_lab/wc_utils/wc_utils/config/core.py", line 15, in <module>
    from wc_utils.util.dict import DictUtil
  File "/home/zl/karr_lab/wc_utils/wc_utils/util/__init__.py", line 1, in <module>
    from . import chem
  File "/home/zl/karr_lab/wc_utils/wc_utils/util/chem/__init__.py", line 1, in <module>
    from .core import EmpiricalFormula, get_major_micro_species, draw_molecule, OpenBabelUtils
  File "/home/zl/karr_lab/wc_utils/wc_utils/util/chem/core.py", line 25, in <module>
    import jnius
  File "/home/zl/.conda/envs/py36/lib/python3.7/site-packages/jnius/__init__.py", line 13, in <module>
    from .reflect import *  # noqa
  File "/home/zl/.conda/envs/py36/lib/python3.7/site-packages/jnius/reflect.py", line 15, in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
  File "/home/zl/.local/lib/python3.7/site-packages/six.py", line 827, in __new__
    return meta(name, bases, d)
  File "jnius/jnius_export_class.pxi", line 114, in jnius.MetaJavaClass.__new__
  File "jnius/jnius_export_class.pxi", line 164, in jnius.MetaJavaClass.resolve_class
  File "jnius/jnius_env.pxi", line 11, in jnius.get_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 90, in jnius.get_platform_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 59, in jnius.create_jnienv
SystemError: Error calling dlopen(b'/usr/lib/jvm/java-11-openjdk-amd64/jre/lib/amd64/server/libjvm.so': b'/usr/lib/jvm/java-11-openjdk-amd64/jre/lib/amd64/server/libjvm.so: cannot open shared object file: No such file or directory'

**Comment by jonrkarr** [comment]
I pushed a fix for this so that jnius isn't imported when it or its dependencies aren't installed
